#!/usr/bin/env zsh
set -euo pipefail

pomodoro() {
	split="${1:-}"
	if [[ -z "$split" ]]; then
		split=$(gum choose "25/5" "50/10" "50-40-30-20-10" "custom" "done" --header "Choose split times:")
	fi
	
	case "$split" in
		"25/5")
		work_time="25m"
		break_time="5m"
		;;
		"50/10")
		work_time="50m"
		break_time="10m"
		;;
		"50-40-30-20-10")
		recurring=1
		work_time="50m"
		break_time="10m"
		;;
		"custom")
		work_time="$(gum input --prompt "Choose work time(mins):")m"
		break_time="$(gum input --prompt "Choose break time(mins):")m"
		;;
		"recurring")
		;;
		"done"|"")
		exit 0
		;;
	esac
	
	timer "$work_time" && osascript -e 'display notification "Pomodoro" with title "Work time is up! Time for a break!" sound name "Crystal" '

	if gum confirm "Do you want to take the ${break_time} break?"; then
		timer "$break_time" && osascript -e 'display notification "Pomodoro" with title "Break time is up! Time to work!" sound name "Crystal" '
	fi
	
	unset split
	if [[ -v recurring ]]; then
        	work_minutes="${work_time%m}"

        	if [[ "$work_minutes" -gt 10 ]]; then
            		work_minutes=$((work_minutes - 10))
            		work_time="${work_minutes}m"
            		pomodoro "recurring"
        	else
			unset recurring
            		pomodoro ""
        	fi
	else
        	pomodoro ""
   	fi
}

pomodoro ""
